hello:
    path: /hello/{prenom}
    controller: App\Controller\HelloWorldController::hello
    requirements:
        prenom: '[a-zA-Z]+'
helloListe:
    path: /hello/liste
    controller: App\Controller\HelloWorldController::helloliste
form:
    path: /form
    controller: App\Controller\HelloWorldController::form
    methods: GET

formReceive:
    path: /form/receive
        controller: App\Controller\HelloWorldController::formReceive
        methods: POST
